### ISSUE TITLE
SEE definition inconsistency

### ISSUE THREAD

**Issue by stemotre** [biometricITC/cPP-biometrics#119] opened 2018-06-06 17:35 UTC
We believe that the current content of the cPP is reliant on the notion of a “Secure Execution Environment”, in an inconsistant manner.

The cPP currently establishes the following statements related to SEE:
- (Section 1.5) SEE is an OE separate from the main Mobile Device OS (isolated by separate security processor, by restricted Access Control, through special processor modes, or a combination)
- (Section 2.4) TOE is inside the SEE
- (Section 2.4) SEE shall be evaluated based on [MDFPP]
- (Section 2.4) SEE is out of scope of the TOE
- (FPT_BDP_EXT.1.1) TSF plaintext biometric data processing is within the SEE
- (FPT_BDP_EXT.2.1) TSF shall not export plaintext biometric data outside the SEE
- (FPT_BDP_EXT.3.1) TSF shall not store plaintext biometric data outside the SEE

The problems that we see are the followings:
- In the [MDFPP], there is no mention of SEE, so no clear SFR that support the claims made in this cPP
- The SEE is not a boundary of the TSF or TOE in this cPP, and it is unclear what responsibility has the TOE/TSF with regards to export and storage: is the TOE required to encrypt the content that goes outside of the SEE? How does the TOE knows what’s SEE versus device OS?
- The latest proposed architecture diagram calls for storage within the SEE, which is not matching the SFR content (FPT_BDP_EXT.3.1)

Proposed resolution:
- The SFR content in this cPP shall focus solely on the TOE and TSFs
- Assumptions and possibly environment objectives are to be defined to incorporate the required notions to support storage, processing and export SFRs
- The architecture diagram shall discuss plaintext storage in SEE versus secure storage outside SEE (and cPP define “secure" and responsibility of TOE/TSF)

**Comment by BrJu** [comment] 2018-06-06 20:44
To be linked also with the wording discussed in #85

**Comment by n-kai** [comment] 2018-06-07 06:35
@stemotre 

- In the [MDFPP], there is no mention of SEE, so no clear SFR that support the claims made in this cPP

As you mentioned, current MDFPP doesn’t define the SEE. However, MDFPP implicitly assumes that the mobile device provides the SEE. For example, FCS_CKM_EXT.1.2 in MDFPP requires that “Each REK shall be hardware-isolated from Rich OS on the TSF in runtime”. This requirement can’t be satisfied without the SEE. Validation report (*1) for MDFPP evaluation also explains how the SEE (e.g. Secure Enclave) contribute to satisfy those MDFPP requirements. So MDFPP doesn’t mention the SEE, but MDFPP evaluation is not possible without the SEE.

*1) Assurance Activity Report for Apple iPad and iPhone Mobile Devices with iOS 11.2
https://www.niap-ccevs.org/MMO/Product/st_vid10851-aar.pdf

Only thing our iTC can do is just waiting for the development of MDFPP and DSC PP so that our cPP can firmly assume that the evaluated mobile device provide the secure SEE in the future (or we can submit the change proposal to the MDFPP for the SEE evaluation).

- The SEE is not a boundary of the TSF or TOE in this cPP, and it is unclear what responsibility has the TOE/TSF with regards to export and storage: is the TOE required to encrypt the content that goes outside of the SEE? How does the TOE knows what’s SEE versus device OS?

If the SEE provides secure memory (e.g. memory area that only Secure Enclave can access) and all plaintext biometric data is stored in such secure memory, FPT_BDP_EXT.3 can be deemed as satisfied because the plaintext biometric data is not stored outside the SEE. However, if the data is moved outside the SEE, the plaintext biometric data shall be encrypted before the data goes outside of the SEE. This encryption may not be done by the biometric system but done by the other part of mobile device. So, this FPT_BDP_EXT.3 may be out of scope of the biometric system, however, we agreed that “SFRs related to core biometric function (biometric verification/performance, PAD) and protection of biometric data (e.g. template) and management of those function, all of which are within the logical scope of the TOE, will be defined in the cPP” (this implicitly means that the TOE scope = biometric system + modules that protect the biometric data) as recorded in the #69.
I am not sure what “How does the TOE knows what’s SEE versus device OS?” means but we can discuss this later.

- The SFR content in this cPP shall focus solely on the TOE and TSFs

I assume that the TOE is biometric system and modules that work for protection of biometric data. Could you tell me your TOE scope?

- Assumptions and possibly environment objectives are to be defined to incorporate the required notions to support storage, processing and export SFRs

As discussed at #69 , we examined that what SFRs should be defined in MDFPP and cPP and I added the Annex A in the cPP to explain the relation between MDFPP SFRs and environment objective in the cPP. Could you tell me what assumption or objectives should be added to the cPP?

We can update the architecture diagram after discussing above items.

**Comment by n-kai** [comment] 2018-06-07 14:35
@stemotre @woodbe will make a pull request to update FPT_BDP_EXT.3 etc.

**Comment by woodbe** [comment] 2018-06-07 17:58
@stemotre 

For FPT_BDP_EXT.2.1, for that point in the iOS security guide about transferring diagnostic data, would that need to be covered here? My concern is again that the TOE is probably not what is doing this transfer but it is the TOE environment (i.e. iOS is transferring diagnostic data that includes diagnostic information from the Secure Enclave), and so further protection of the data at that point is outside the scope of the TOE, but technically still meets this requirement because it isn't transmitted in the clear.

I am thinking that this doesn't need any change with the other updates, but wanted to be sure what you though.

**Comment by n-kai** [comment] 2018-06-08 00:58
@stemotre 
You can specify the evaluated configuration in the ST which means that you can say that diagnostic mode is out of scope of the evaluation in the ST. Japan allows such evaluation (however you have to explain that only authorized user can turn on the diagnostic mode) and I believe that other CC certification bodies also allow this.

**Comment by BrJu** [comment] 2018-06-21 14:30
@gregott will ask internally to NIAP to check diagnostic mode constraint wrt ST
(remaining of the issue is covered by #118  )

**Comment by BrJu** [comment] 2018-07-18 17:16
@gregott any update?

**Comment by gregott** [comment] 2018-08-23 13:37
I have been out of the country for several weeks and am just now getting back to this.  I asked the question before I left but do not see a reply.  Let me ping NIAP again.

**Comment by woodbe** [comment] 2019-01-24 16:02
This will be closed at this time based on agreement that this should be acceptable (the diagnostic mode). May be raised again in the future.

**Closed by woodbe** 2019-01-24 16:02 UTC
Labels: Mobile use case
